#!/bin/bash

## install picom with rounded corners and kawase blur
# git clone https://aur.archlinux.org/picom-ibhagwan-git.git
# cd picom-ibhagwan-git
# makepkg -si --noconfirm
# cd ..

# fonts
cp ./fonts/* /usr/share/fonts/

# configs
cp config/rofi/* ~/.config/rofi
cp config/qtile/* ~/.config/qtile
cp config/picom/* ~/.config/picom
cp config/zsh/* ~
cp config/tmux/.tmux.conf ~/.tmux.conf

echo Installation finished.
