#!/bin/bash

git clone https://github.com/ibhagwan/picom
cd picom
makepkg -si
cd ..

#fonts
sudo cp ./fonts/* /usr/share/fonts/

# configs
sudo cp -r .config/* ~/.config/

# wallpapers
sudo cp -r ./wallpapers/* ~/Pictures/wallpapers

echo Installation finished.
