#!/bin/bash

git clone https://aur.archlinux.org/picom-ibhagwan-git.git
cd picom-ibhagwan-git
makepkg -si --noconfirm
cd ..

#fonts
sudo cp ./fonts/* /usr/share/fonts/

# configs
sudo cp -r .config/* ~/.config/

# wallpapers
sudo cp -r ./wallpapers/* ~/Pictures/wallpapers

echo Installation finished.
